project:
  type: website
  output-dir: ../docs
  

website:
  title: "PM566 final website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Data Tables.qmd
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

